<a href="https://colab.research.google.com/github/Ralein/AI-ML/blob/colab/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a = [1,2,3,4,5]
b = np.array(a)
print(type(b))
c=np.zeros((4,5))
print(c)
d=np.ones((2,2))
print(d)


<class 'numpy.ndarray'>
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
v = np.arange(1,40,2)
print(v)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [ ]:
q = np.linspace(1,10,100)
print(q)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [ ]:
#additional information - attributes

v.ndim
v.shape
v.size
v.dtype
v.itemsize

8

In [ ]:
#universal function & aggregate function

#universal function - sqrt, sin(algebra related function)
np.sqrt([1,2,3])



array([1, 2, 3])

In [ ]:
np.abs([1,2,3])


array([1, 2, 3])

In [ ]:
#aggregate(sum, min, max, mean, std)

In [ ]:
print(np.sum([1,2,3,4]))

10


In [ ]:
#numpy 500 universal function+
print(np.cbrt([1,2,3,4]))

[1.         1.25992105 1.44224957 1.58740105]


In [ ]:
import numpy as np

print(np.exp([1,2,3,4]))
print(np.sqrt([1,2]))
print(np.square([3,4]))
print(np.cbrt([64]))
print(np.reciprocal([1,2,4,5]))
print(np.sign([-10,0,10]))
print(np.abs([-1,-2,3,-4]))
print(np.fabs([-1.5,-2.3,3.2]))
print(np.ceil([1.2,2.3,3]))
print(np.rint([1.2,2.6,3]))
print(np.trunc([1.8,2.9,3]))

print(np.log10([1,10]))
print(np.log2([1,2,4,8]))
print(np.expm1([1,2,3]))
print(np.log1p([1,2,3]))
print(np.degrees([np.pi/2, np.pi]))
print(np.radians([90,180]))
print(np.sin(np.pi/2))
print(np.cos(np.pi))
print(np.tanh([1,2,3]))

print(np.add([1,2,3],[4,5,6]))
print(np.subtract([10,20,30],[1,2,3]))
print(np.multiply([1,2,3],[4,5,6]))

print(np.divide([10,20,30],[2,4,5]))
print(np.power([2,3,4],[2,2,2]))
print(np.maximum([1,5,3],[2,4,6]))
print(np.minimum([1,5,3],[2,4,6]))
print(np.fmax([1,np.nan,3],[2,4,6]))
print(np.fmin([1,np.nan,3],[2,4,6]))
print(np.mod([10,20,30],[1,2,3]))
print(np.remainder([10,20,30],[1,2,3]))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.         1.41421356]
[ 9 16]
[4.]
[1 0 0 0]
[-1  0  1]
[1 2 3 4]
[1.5 2.3 3.2]
[2. 3. 3.]
[1. 3. 3.]
[1. 2. 3.]
[0. 1.]
[0. 1. 2. 3.]
[ 1.71828183  6.3890561  19.08553692]
[0.69314718 1.09861229 1.38629436]
[ 90. 180.]
[1.57079633 3.14159265]
1.0
-1.0
[0.76159416 0.96402758 0.99505475]
[5 7 9]
[ 9 18 27]
[ 4 10 18]
[5. 5. 6.]
[ 4  9 16]
[2 5 6]
[1 4 3]
[2. 4. 6.]
[1. 4. 3.]
[1 6 3]
[1 6 3]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.percentile(arr, 50))
print(np.quantile(arr, 0.5))
print(np.average(arr))
print(np.nanmean([1,2,np.nan,4]))
print(np.nansum([1,2,np.nan,4]))
print(np.nanmin([1,2,np.nan,4]))
print(np.nanmax([1,2,np.nan,4]))
print(np.sum([[1,2],[3,4]], axis=0))
print(np.sum([[1,2],[3,4]], axis=1))

15
120
3.0
3.0
1.4142135623730951
2.0
1
5
0
4
3.0
3.0
3.0
2.3333333333333335
7.0
1.0
4.0
1.247219128924647
1.5555555555555554
15.0
3.0
[4 6]
[3 7]


In [ ]:
import numpy as np
arr = np.arange(21,30).reshape((3,3))
element = arr[1,2]
print(element)

26


In [ ]:
#Array Manipulation
import numpy as np

x = [[1,2,3], [3,4,5]]
arr = np.array(x)
print(arr)
arr1 = np.reshape(arr, (3,2))
arr2 = np.ravel(arr) #change to 2d to 1d
arr3 = np.transpose(arr) #changes rows->column viseversa
print(arr1)
print(arr2)


[[1 2 3]
 [3 4 5]]
[[1 2]
 [3 3]
 [4 5]]
[1 2 3 3 4 5]


In [ ]:
#splitting array & joining array